### ISSUE TITLE
Add Docker image to Docker Hub automated builds

### ISSUE THREAD

**Issue by jacksegal** [jacksegal/google-compute-snapshot#86]
(taken from PR #83 )

At the moment the Docker image is automagically built via [Docker Hub automated builds](https://hub.docker.com/r/djjudas21/google-compute-snapshot/) from @djjudas21 Github fork of this project. 

Need to set up automated builds from the master repo & then update README with new URL.

@djjudas21 is happy to explain how to do this.

**Comment by jacksegal** [comment]
Hi @djjudas21 

I've had a go at setting up an automated build: https://hub.docker.com/r/jacksegal/google-compute-snapshot/

Can you have a look and let me know if it's correct?  Mine doesn't have the "Dockerfile" or "Builds" tab that yours does.

Thanks,
Jack

**Comment by jacksegal** [comment]
Thanks @djjudas21 - the last push I did on 7th Jan triggered an automated build on Docker Hub, so I've updated the README with the URL my repo.

Thanks for your contribution 👍

**Comment by djjudas21** [comment]
I'm still not 100% sure if this is working properly. On [my Docker hub page](https://hub.docker.com/r/djjudas21/google-compute-snapshot/) it shows tabs for _Dockerfile_ and _Builds_, and on the right hand side there is a link for _Source Repository_. [Yours](https://hub.docker.com/r/jacksegal/google-compute-snapshot/) doesn't have any of those, so does this mean it's a non-automated build?

From what I recall, I didn't create the Docker Hub repo manually, I just followed the wizard to add an automated build, linked it to the Github project and it did the rest itself. Is this what you did?

Also, I spotted in your `README` it still points people towards my Docker image, rather than yours :smile:
